# Generated by Django 4.0.4 on 2022-06-16 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_userprofile_bio_alter_post_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='github_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='linkedin_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='website_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Fullstack', 'Fullstack'), ('Frontend', 'Frontend'), ('Cyber Security', 'Cyber Security'), ('Web3', 'Web3'), ('AWS-DevOps', 'AWS-DevOps'), ('Backend', 'Backend'), ('Salesforce', 'Salesforce')], max_length=20),
        ),
    ]
